sd_a_welcome_homepage:
    pattern:  /
    defaults: { _controller: SdAWelcomeBundle:Welcome:index }

sd_a_welcome_about:
    pattern:  /about
    defaults: { _controller: SdAWelcomeBundle:Welcome:about }
