<?php

namespace SdA\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('id' => 'DESC'));
	}
	
	public function getArticlesByCategorie($categorie)
	{
		$qb = $this->createQueryBuilder('article');
		$qb->join('article.categories', 'c')->where('c.nom = :categorie')->setParameter('categorie', $categorie) ;
	
		return $qb->getQuery()->getResult();
	}
}
