parameters:
#    sd_a_core.example.class: SdA\CoreBundle\Example

services:
#    sd_a_core.example:
#        class: %sd_a_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
